baseURL = 'https://myvar.dev/'
languageCode = 'en-US'
title = 'MyVar.dev'
theme = 'default'
enableRobotsTXT = true

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

  [[menus.main]]
    name = 'Search'
    url = '#'
    weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[params]
  Description = 'Practical coding tutorials and articles designed for developers who build things'

[markup]
  [markup.highlight]
    style = 'dracula'

[minify]
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepDefaultAttrVals = false
      keepSpecialComments = false
    [minify.tdewolff.js]
      version = 2024